### ISSUE TITLE
App crashes from a Null pointer exception if the file selected to play has been deleted or moved

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#17]
If you run the app, switch out of it, delete or move or rename the file, and switch back, then try to play it, the app crashes with the following exception;

>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.musicplayer, PID: 16053
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.musicplayer/com.example.SocyMusic.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.start()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.start()' on a null object reference
        at com.example.SocyMusic.PlayerActivity.onCreate(<ins>PlayerActivity.java:112</ins>)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Benji377** [comment]
Thank you very much for your report. I saw you even fixed it right away. You are great, thank you!

**Comment by squivix** [comment]
> Thank you very much for your report. I saw you even fixed it right away. You are great, thank you!

I didn't fix THIS issue though. I just added a message for when no songs are found so that the user isn't confused by a blank screen that gives no info.

This issue is different. The issue is when a song is found and shows up on the ListView but then the user goes away from the app, deletes the song, and comes back. The list is not updated and the song is still there. Clicking on it causes the app to crash with a null pointer exception. To fix this you can either make the app update the list view every time it pauses and resumes (which may be unnecessary) or at least make it not attempt to play a file if it finds it to be unavailable after initially loading it. That is by catching  the exception and displaying some sort of error message. I'm gonna try to fix this now.

**Comment by Benji377** [comment]
Oh. You are right

**Comment by squivix** [comment]
Ok now I fixed the crashing but the list is still not refreshing. I'm wondering why mySongs in MainActivity is a local variable not a field? It has to be final because of that, so I can't make it look for songs again in files...
